services:
    - type: web
      plan: Pro
      name: mysite
      runtime: python
      region: Singapore
      buildCommand: "./build.sh"
      startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: poppindb
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
