databases:
  - name: poppindb
    plan: free
    databaseName: poppindb
    user: poppindb
    region: singapore

services:
  - type: web
    plan: free
    name: poppin
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poppindb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4